### ISSUE TITLE
Deploy to NPM?

### ISSUE THREAD

**Issue by jbcpollak** [sverweij/mscgen_js#206]
Any thought to deploying this to npm to make it usable as a module?

**Comment by sverweij** [comment]
Good question. Some thoughts:

-  It'd mean mscgen_js would need to run in node.js just as well as in the browser. That needs work. I'll need to hack around the lack of getBBox support in [jsdom](https://github.com/tmpvar/jsdom) or find an alternative for jsdom. 
  - Most affected are texts and boxes behind and around them that need resizing.
  - For many charts the output is close, but not close enough for my taste... 
- Rendering to png/ jpg uses canvas. Doing that in node.js with jsdom should be possible with some plumbing only, but I haven't researched it too deeply yet.
- Parsing and translating to text formats work just as well in node.js as in the browser, so those  that could be released as one or modules (after doing some npm pyrotechnics :-) )

 => What is your use case/ what triggered your question?

**Comment by jbcpollak** [comment]
Hum, I wonder if you could use phantomjs to get a DOM? I guess that might be a bit clunky.

I was trying to figure out how to use the project with a static website generator like hexo.io, but I didn't realize you can embed mscgen_js into a website. Is it possible to do that and load the msc source from a separate file? Also can the compiled JS file be loaded as a bower dependency?

**Comment by sverweij** [comment]
- Phantomjs: I've been playing around with it for testing purposes. I agree it feels a bit clunky, and I'll have to look into the glue-work but if the performance is good enough (and installing isn't too much of a hassle...) why not. I'll keep it in mind.

- Loading from a separate msc source file is possible, but it'd mean the inpage script would need to do an ajax call to retrieve it. 
- Would that be usable enough for a static website? 
  - There's more files to load, so will be slower.
  - when running it from file:// it won't work on webkit browsers.

- Publishing as a bower package: good plan. It has just landed somewhere in the top of my todo list (no guarantees) :-) .

**Comment by jbcpollak** [comment]
I don't mind making separate ajax calls - what if like to be able to do is
write a single page app that loads the MSC and renders it.

I'll make a separate issue for bower, and you can prioritize it as you can!

**Comment by sverweij** [comment]
A bower package with only the mscgen-inpage.js is now available, so you can load it as a dependency
```
bower install mscgen_js-inpage-package
```

**Comment by jbcpollak** [comment]
Thats great, thanks!
