### ISSUE TITLE
Create Atom package for rendering

### ISSUE THREAD

**Issue by nicktimko** [sverweij/mscgen_js#215]
It would be neat to have rendering with live-update inside Atom, a la the [Markdown Preview](https://github.com/atom/markdown-preview). It works great in the browser, but then to save the figure I end up copy-pasting into my text editor.

Fantastic tool, btw.

**Comment by sverweij** [comment]
Yes, that would be _awesome_ !

I have no idea what I'm getting into, though, so timelines are :foggy: at best (and help is welcome).

Thanks for the kind words :blush:

**Comment by sverweij** [comment]
Dabbled in atom dev this weekend:
- Prerequisite for a decent previewer is language support.
- Atom ~~doesn't~~ didn't have MscGen language support.
- It now does, see
  - [package *language-mscgen* on atom.io](https://atom.io/packages/language-mscgen)
  - github repo: https://github.com/sverweij/atom-language-mscgen

Previewer is doable, but _definitely_ not a 1 storypoint story :eyes:

**Comment by sverweij** [comment]
@nicktimko something like this?
- It's working, but needs polishing before it can be published to atom.io. 
- github repo: https://github.com/sverweij/atom-mscgen-preview

![preview-mscgen](https://cloud.githubusercontent.com/assets/4822597/11170822/1d8c5e0e-8be0-11e5-8ced-ebab7d5c1780.gif)

**Comment by nicktimko** [comment]
That is kick ass. Excellent work!

**Comment by sverweij** [comment]
Polishing done, so
- I just published the ("minimal viable") [mscgen-preview package to atom.io](https://atom.io/packages/mscgen-preview) 
- Should be installable from within atom. 
- _Includes_ the syntax highlighting from `language-mscgen` (see above).
- Preview with ctrl-shift-G (Msc**G**en ;-) ) in *.mscgen, *.mscin, *.msc, *.xu and *.msgenny

Issues are welcome in the repo: 
https://github.com/sverweij/atom-mscgen-preview/issues  

Enjoy!
