### ISSUE TITLE
Text labels are slightly translucent

### ISSUE THREAD

**Issue by Wargazm** [sverweij/mscgen_js#229]
All text labels are slightly translucent.  See this example input.

    
    a,b,c;

    a note a : a note a\n(note),
    b box b  : b box b\n(action);
    a rbox a : a rbox a\n(reference),
    b abox b : b abox b\n(state/ condition);

    a -> c : [label="This one too"];

If you look closely, the vertical lines for A and C can be seen through all of the text labels.  

Can text labels be made 100% opaque?

**Comment by sverweij** [comment]
You've got a sharp eyes!

- I introduced the 10% translucent text backgrounds deliberately when the text wrapping algorithm occluded arcs a lot more often then right now (see example below). With the translucency arrows remained (sort of...) visible.
- For boxes this was not necessary, strictly speaking. But to keep colors consistent between boxes and labels, they use the same translucency nevertheless.

Since then (2013 ...) I have redone the wrapping algorithm, and occlusion happens a lot less, even with `autowrap=on`, so I'd like to try what happens when the translucency is switched off. The change is fairly trivial, but I need some time to publish it - I'll share the url in an update

... out of curiosity:
=> What is the reason you want labels to be 100% opaque?

### example of text occlusion
```
a =>> b: "First line.\nSecond line; occludes.\nThird line.";
```
![occlusion](https://cloud.githubusercontent.com/assets/4822597/13681543/f2e3ee00-e6fd-11e5-8a3e-89616335fca1.png)

**Comment by Wargazm** [comment]
I see!  Thanks for the explanation.

My personal preference is to minimize opacity in all of my diagrams.  I think that it hurts readability.  For example, in the image you posted, I can understand your rationale for making the text label translucent but I think the arrow flow is just as understandable if the label covered it completely, since the arrow is perfectly horizontal.

I do concede that if you use arcgradient != 0, the translucency could help. Again, it just comes down to personal preference!  

I'm not usually one to like software with *tons* of options, but perhaps something like this could be done?

    msc {

       # default label opacity of 10% can be overrideen by user
       defaultlabelopacity=100; # 0-100, as a percentage

       # Colors accept an optional alpha channel that overrides all defaults 
       
       # White box, completely transparent
       A box A [label="abox", textbgcolour="#ffffff00"]; 
       
       # Red box, Completely opaque 
       A box A [label="rbox", textbgcolour="#ff0000ff"];
       
       # green box, 50% opacity
       A box A [label="note", textbgcolour="#00ff0080"];
       
       # blue box, default
       A box A [label="note", textbgcolour="#0000ff"];
       
    }

**Comment by sverweij** [comment]
I've published a feature branch where the default opacity of everything but watermarks is 100%, just to get a feel of how it looks: http://sverweij.github.io/mscgen_js/branches/feature/opacify/index.html - let me know what you think.

- I'm thinking about a way to get things, like fonts, line width, shadows etc configurable. I hadn't thought to include default text label opacity in that list - thanks for that suggestion!
- I'm leaning towards 100% opacity as a default - as that's what you'd expect 
- B.t.w.: the interpreter accepts all css colors - including those with alpha channels:  `rgba(255, 0, 0, 0.8)` or `transparent` work. Applied to your example:

```
msc {
   # default label opacity of 10% can be overriden by user
   # defaultlabelopacity=100; # 0-100, as a percentage

   # Colors accept an optional alpha channel that overrides all defaults 
   A;

   # White box, completely transparent
   A box A [label="abox", textbgcolour="transparent"]; 

   # Red box, Completely opaque 
   A box A [label="rbox", textbgcolour="rgba(255, 0, 0, 1)"];

   # green box, 50% opacity
   A box A [label="note", textbgcolour="rgba(0, 255, 0, 0.5)"];

   # blue box, default
   A box A [label="note", textbgcolour="rgba(0, 0, 255, 0.9)", textcolour="white"];
}
```

Which renders like so:
![translucency](https://cloud.githubusercontent.com/assets/4822597/13685224/a284bb26-e70f-11e5-8dcf-2e4f122ff1e8.png)

**Comment by sverweij** [comment]
@Wargazm I've been using the _100% opaque version_ for a few days - and it's a keeper. Thanks for bringing it to my attention. 

I've updated mscgenjs-core to reflect this, and updated all stuff using it (in page package, on line interpreter, command line interface, atom package) - so you'll be able to use it as of now.

Enjoy!

**Comment by Wargazm** [comment]
Fantastic!  I'll update all my documents tomorrow. 

Thanks so much for being so prompt and attentive.
