### ISSUE TITLE
Feature request: Option to add labels to bottom of the chart

### ISSUE THREAD

**Issue by oboff** [sverweij/mscgen_js#236]
I'd like to have ability to see the label boxes on bottom row of chart in addition to top row.

**Comment by sverweij** [comment]
How would that help you? In what situations would you use this option?

(B.t.w. I assume you mean something like this?):
![like this?](https://cloud.githubusercontent.com/assets/4822597/15984519/5f360aca-2fce-11e6-880d-a79ccab197a7.png)

**Comment by oboff** [comment]
Yes, exactly that. Especially on mobile, as you go down on sufficiently large diagram, easier to look down and see labels than have to scroll up and lose context tracking back.

**Comment by sverweij** [comment]
Ah, so you're looking to alleviate that 'hunting around' on bigger diagrams. 

Duplicating the entities on the bottom will is one of the solutions; I'll look into it. I'm also looking for other options to improve the 'hunting around' situation. E.g. Freezing the first row. Or an onionskin overlay which shows the entities on hover (/ activate)?

(b.t.w. => do you use sequence charts on mobile/ small displays a lot?)

**Comment by sverweij** [comment]
Onion skin doodad:
![onion-skin](https://cloud.githubusercontent.com/assets/4822597/15993817/502c87aa-30f2-11e6-85c7-46da6dd03a42.gif)

**Comment by sverweij** [comment]
@oboff I've created a PR which adds a `mirrorentitiesonbottom` option to the msgenny and xu languages. By default it is off; enable it like so:

```
mirrorentitiesonbottom=true;

Alice => Bob : do something funny;
Bob => pocket : fetch (nose flute);
Bob >> Alice : PHEEE!;
Alice => Alice: hihihi;
```

I've deployed the feature branch for you to play with:
- [The above chart](http://mscgen.js.org/branches/feature/big-chart-navigation/?lang=msgenny&msc=mirrorentitiesonbottom%3Dtrue%3B%0A%0AAlice%20%3D%3E%20Bob%20%3A%20do%20something%20funny%3B%0ABob%20%3D%3E%20pocket%20%3A%20%22fetch%20(nose%20flute)%22%3B%0ABob%20%3E%3E%20Alice%20%3A%20PHEEE!%3B%0AAlice%20%3D%3E%20Alice%3A%20hihihi%3B)
- ... or with a bigger one: [reCaptcha](https://mscgen.js.org/branches/feature/big-chart-navigation/?lang=xu&msc=xu%20%7B%0A%20%20wordwraparcs%3Dtrue%2C%20mirrorentitiesonbottom%3Dtrue%3B%0A%0A%20%20customer%20%5Blinecolor%3Dred%2C%20%20arclinecolor%3Dred%2C%20%20textbgcolor%3D%22%23FFCCCC%22%5D%2C%0A%20%20client%20%20%20%5Blinecolor%3Dblue%2C%20arclinecolor%3Dblue%2C%20textbgcolor%3D%22%23CCCCFF%22%5D%2C%0A%20%20server%20%20%20%5Blinecolor%3Dblue%2C%20arclinecolor%3Dblue%2C%20textbgcolor%3D%22%23CCCCFF%22%5D%2C%0A%20%20google%20%20%20%5Blabel%3D%22Google%20reCaptcha%20service%22%2C%20linecolor%3Dfuchsia%2C%20arclinecolor%3Dfuchsia%2C%20textbgcolor%3D%22%23FFCCFF%22%5D%3B%0A%0A%20%20customer%20%3D%3E%20client%20%5Blabel%3D%22log%20in%20with%20credentials%2C%20reCaptcha%22%5D%3B%0A%20%20client%20%20%20%3D%3E%20google%20%5Blabel%3D%22getResponse(reCaptcha)%22%5D%3B%0A%20%20google%20%20%20%3E%3E%20client%20%5Blabel%3D%22reCaptcha%20response%22%5D%3B%0A%20%20client%20%20%20%3D%3E%20server%20%5Blabel%3D%22POST%20credentials%2C%20reCaptcha%20response%22%5D%3B%0A%20%20server%20%20%20%3D%3E%20google%20%5Blabel%3D%22POST%20reCaptcha%20response%2C%20secret%22%5D%3B%0A%20%20customer%20alt%20google%20%5Blabel%3D%22reCaptcha%20valid%22%2C%20linecolor%3D%22grey%22%2C%20textbgcolor%3D%22white%22%5D%20%7B%0A%20%20%20%20google%20%20%20%3E%3E%20server%20%5Blabel%3D%22OK%22%5D%3B%0A%20%20%20%20server%20rbox%20server%20%5Blabel%3D%22check%20hostname%2C%20error%20codes%22%5D%3B%0A%20%20%20%20server%20rbox%20server%20%5Blabel%3D%22do%20regular%20login%20processing%22%5D%3B%0A%0A%20%20%20%20---%20%5Blabel%3D%22reCaptcha%20not%20valid%22%2C%20linecolor%3Dgrey%2C%20textbgcolor%3Dwhite%5D%3B%0A%20%20%20%20google%20%3E%3E%20server%20%20%20%5Blabel%3D%22NOK%22%5D%3B%0A%20%20%20%20server%20%3E%3E%20client%20%20%20%5Blabel%3D%22HTTP%2040x%20%27reCaptcha%27%22%5D%3B%0A%20%20%20%20client%20%3E%3E%20customer%20%5Blabel%3D%22sorry%20dude%20-%20captcha%20didn%27t%20check%20out%22%5D%3B%0A%0A%20%20%20%20---%20%5Blabel%3D%22other%20error%20and%2F%20or%20time-out%22%2C%20linecolor%3Dgrey%2C%20textbgcolor%3Dwhite%5D%3B%0A%20%20%20%20...%2C%20google%20-x%20server%3B%0A%20%20%20%20server%20note%20client%20%5Blabel%3D%22Treating%20this%20as%20an%20error%20will%20mean%20your%20log%20in%20won%27t%20work%20when%20the%20reCaptcha%20service%20is%20down.%5Cn%5CnIt%20depends%20on%20the%20gig%20what%20you%20actually%20do%20here%3A%5Cn%5Cn-%20safety%20before%20everything%20shop%3A%20throw%20an%20error%5Cn-%20acceptable%20risk%20vs%20revenue%20shop%3A%20do%20regular%20login%22%2C%20linecolor%3D%22black%22%2C%20textbgcolor%3D%22%23FFFFCC%22%5D%3B%0A%20%20%20%20server%20%3E%3E%20client%20%20%20%5Blabel%3D%22Error%20(HTTP%20500%3F)%22%5D%3B%0A%20%20%20%20client%20%3E%3E%20customer%20%5Blabel%3D%22sorry%20dude%22%5D%3B%0A%20%20%7D%3B%0A%7D%0A)

=> Let me know what you think!

Some notes:
- You'll see the syntax highlighting doesn't recognize it yet - codemirror's mscgen mode (which also covers msgenny and xù) isn't updated (yet).
- I have some doubts whether I should keep this as part of the language(s) or a separate render option (like the experimental stylesheet feature in the [atom mscgen preview package](https://github.com/sverweij/atom-mscgen-preview))
- I have tried the onion skin thing and while the concept still appeals (and is a potentially better solution), getting the UX right is not easy.

**Comment by sverweij** [comment]
@oboff a little change in plans:
- I've kicked the option out of the languages - it doesn't belong there.
- In stead I moved it to an option in the render engine.
- It's available in the UI: 
  - in the (new) options menu (behind the cog-wheel)
  - by passing a `mirrorentities` parameter: https://mscgen.js.org/branches/feature/big-chart-navigation//index.html?mirrorentities=true)

Here's a [simple sample](https://mscgen.js.org/branches/feature/big-chart-navigation/index.html?lang=msgenny&debug=true&mirrorentities=true&msc=Alice %3D> Bob %3A do something funny%3B%0ABob %3D> pocket %3A "fetch (nose flute)"%3B%0ABob >> Alice %3A PHEEE!%3B%0AAlice %3D> Alice%3A hihihi%3B), and here's a [less simple sample](https://mscgen.js.org/branches/feature/big-chart-navigation/?lang=xu&msc=xu%20%7B%0A%20%20wordwraparcs%3Dtrue%3B%0A%0A%20%20customer%20%5Blinecolor%3Dred%2C%20%20arclinecolor%3Dred%2C%20%20textbgcolor%3D%22%23FFCCCC%22%5D%2C%0A%20%20client%20%20%20%5Blinecolor%3Dblue%2C%20arclinecolor%3Dblue%2C%20textbgcolor%3D%22%23CCCCFF%22%5D%2C%0A%20%20server%20%20%20%5Blinecolor%3Dblue%2C%20arclinecolor%3Dblue%2C%20textbgcolor%3D%22%23CCCCFF%22%5D%2C%0A%20%20google%20%20%20%5Blabel%3D%22Google%20reCaptcha%20service%22%2C%20linecolor%3Dfuchsia%2C%20arclinecolor%3Dfuchsia%2C%20textbgcolor%3D%22%23FFCCFF%22%5D%3B%0A%0A%20%20customer%20%3D%3E%20client%20%5Blabel%3D%22log%20in%20with%20credentials%2C%20reCaptcha%22%5D%3B%0A%20%20client%20%20%20%3D%3E%20google%20%5Blabel%3D%22getResponse(reCaptcha)%22%5D%3B%0A%20%20google%20%20%20%3E%3E%20client%20%5Blabel%3D%22reCaptcha%20response%22%5D%3B%0A%20%20client%20%20%20%3D%3E%20server%20%5Blabel%3D%22POST%20credentials%2C%20reCaptcha%20response%22%5D%3B%0A%20%20server%20%20%20%3D%3E%20google%20%5Blabel%3D%22POST%20reCaptcha%20response%2C%20secret%22%5D%3B%0A%20%20customer%20alt%20google%20%5Blabel%3D%22reCaptcha%20valid%22%2C%20linecolor%3D%22grey%22%2C%20textbgcolor%3D%22white%22%5D%20%7B%0A%20%20%20%20google%20%20%20%3E%3E%20server%20%5Blabel%3D%22OK%22%5D%3B%0A%20%20%20%20server%20rbox%20server%20%5Blabel%3D%22check%20hostname%2C%20error%20codes%22%5D%3B%0A%20%20%20%20server%20rbox%20server%20%5Blabel%3D%22do%20regular%20login%20processing%22%5D%3B%0A%0A%20%20%20%20---%20%5Blabel%3D%22reCaptcha%20not%20valid%22%2C%20linecolor%3Dgrey%2C%20textbgcolor%3Dwhite%5D%3B%0A%20%20%20%20google%20%3E%3E%20server%20%20%20%5Blabel%3D%22NOK%22%5D%3B%0A%20%20%20%20server%20%3E%3E%20client%20%20%20%5Blabel%3D%22HTTP%2040x%20%27reCaptcha%27%22%5D%3B%0A%20%20%20%20client%20%3E%3E%20customer%20%5Blabel%3D%22sorry%20dude%20-%20captcha%20didn%27t%20check%20out%22%5D%3B%0A%0A%20%20%20%20---%20%5Blabel%3D%22other%20error%20and%2F%20or%20time-out%22%2C%20linecolor%3Dgrey%2C%20textbgcolor%3Dwhite%5D%3B%0A%20%20%20%20...%2C%20google%20-x%20server%3B%0A%20%20%20%20server%20note%20client%20%5Blabel%3D%22Treating%20this%20as%20an%20error%20will%20mean%20your%20log%20in%20won%27t%20work%20when%20the%20reCaptcha%20service%20is%20down.%5Cn%5CnIt%20depends%20on%20the%20gig%20what%20you%20actually%20do%20here%3A%5Cn%5Cn-%20safety%20before%20everything%20shop%3A%20throw%20an%20error%5Cn-%20acceptable%20risk%20vs%20revenue%20shop%3A%20do%20regular%20login%22%2C%20linecolor%3D%22black%22%2C%20textbgcolor%3D%22%23FFFFCC%22%5D%3B%0A%20%20%20%20server%20%3E%3E%20client%20%20%20%5Blabel%3D%22Error%20(HTTP%20500%3F)%22%5D%3B%0A%20%20%20%20client%20%3E%3E%20customer%20%5Blabel%3D%22sorry%20dude%22%5D%3B%0A%20%20%7D%3B%0A%7D%0A)

![look-in-the-mirror](https://cloud.githubusercontent.com/assets/4822597/16174154/ab64d816-35b6-11e6-8787-ced2e9fefcdc.gif)

**Comment by oboff** [comment]
That's perfect!
