### ISSUE TITLE
Entity header text wraps

### ISSUE THREAD

**Issue by daledude** [sverweij/mscgen_js#246]
### Expected Behavior

How would I get the lines of the event-text to not wrap? I'm using "wordwraparcs=false" but it's not working and probably isn't supposed to for the headers.

### Steps to Reproduce (for bugs)

See the bookmarked graph [here](https://mscgen.js.org/?lang=mscgen&msc=msc%20%7B%0A%20%20width%3Dauto%2Cwordwraparcs%3Dfalse%3B%0A%22111.222.333.444%22%5Blabel%3D%22Echo%20144%5Cn111.222.333.444%22%2Clinecolor%3D%22%23c0c0c0%22%5D%2C%22SBC%22%5Blabel%3D%22%5CnSBC%22%2Clinecolor%3D%22%23c0c0c0%22%5D%2C%2255.555.555.555%22%5Blabel%3D%22TOOLS%5Cn55.555.555.555%22%2Clinecolor%3D%22%23c0c0c0%22%5D%2C%22666.66.666.666%22%5Blabel%3D%22please-dont-wrap%5Cn666.66.666.666%22%2Clinecolor%3D%22%23c0c0c0%22%5D%2C%22SPACER1%22%20%5Barclinecolor%3D%22white%22%2C%20arctextcolor%3D%22%23c0c0c0%22%2C%20linecolor%3D%22white%22%2C%20textcolor%3D%22white%22%5D%3B%0A%7D).

Most of the headers have 2 lines. Top is text and the second is an IP address.

Maybe worth noting is that I can have anywhere from 2 to 12 entity headers. I currently use logic to set the width depending on how may. If under 6 then set width=auto otherwise over 6 I dynamically calculate the width.

### Your Environment

* Version used: 1.9
* Browser Name and version: Chrome 57.0.2987.110
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by sverweij** [comment]
I agree that doesn't look very nice.

As you already surmised `wordwraparcs` is to switch auto wrapping of text on `arcs` ("messages"  in other modelling language speak) and not on entities or any of the other box-like elements. 

Wrapping text in boxes is a bit of a balancing act. You don't want text to trespass the box boundaries; you don't want to chop words half way (like in your example).

_Auto wrap_
The current default. The algorithm is ok in most cases, but not in all - like in your example. And in this one :-/
<img width="303" alt="screen shot 2017-03-31 at 22 46 37" src="https://cloud.githubusercontent.com/assets/4822597/24568902/27e814b4-1664-11e7-8b7d-86889e15bdfd.png">

_Fit box to content_
<img width="447" alt="screen shot 2017-03-31 at 22 22 32" src="https://cloud.githubusercontent.com/assets/4822597/24568110/efd2f916-1660-11e7-98e9-64047fa4174d.png">

_Just don't wrap_
And make wrapping totally manual. E.g. without any manual line breaks:
<img width="336" alt="screen shot 2017-03-31 at 22 17 58" src="https://cloud.githubusercontent.com/assets/4822597/24567925/072d6b56-1660-11e7-8fec-d63577ec035d.png">

... and with some choice manual line breaks
<img width="304" alt="screen shot 2017-03-31 at 22 45 56" src="https://cloud.githubusercontent.com/assets/4822597/24568919/36d96e46-1664-11e7-963d-8bef82a5de80.png">

=> I think this about what you expect (check?)

That'd mean introducing one or two options to the _xù_ and _msgenny_ languages, e.g. `wordwrapentities` and `wordwrapboxes`.

**Comment by sverweij** [comment]
@daledude 
I've added the options `wordwrapentities` and `wordwrapboxes`. They work the same as the `wordwraparcs` option, except they work on entities and boxes respectively and are `true` by default (so if you leave them out sequence charts render in a backward compatible manner).

I've applied the former to the sample you provided  - [here's the sample you provided with the `wordwrapentities` option on false](https://mscgen.js.org/?lang=xu&msc=msc%20%7B%0A%20%20width%3D%22auto%22%2C%0A%20%20wordwraparcs%3Dfalse%2C%0A%20%20wordwrapentities%3Dfalse%3B%0A%0A%20%20%22111.222.333.444%22%20%5Blabel%3D%22Echo%20144%5Cn111.222.333.444%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20SBC%20%5Blabel%3D%22%5CnSBC%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20%2255.555.555.555%22%20%5Blabel%3D%22TOOLS%5Cn55.555.555.555%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20%22666.66.666.666%22%20%5Blabel%3D%22please-dont-wrap%5Cn666.66.666.666%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20SPACER1%20%5Blinecolor%3D%22white%22%2C%20textcolor%3D%22white%22%2C%20arclinecolor%3D%22white%22%2C%20arctextcolor%3D%22%23c0c0c0%22%5D%3B%0A%0A%7D).

I need some time to do some little things (update the documentation, tweak the syntax highlighting for codemirror, atom and visual studio code to name a few) before actually releasing version 1.10.0 everywhere, but mscgen.js.org already has it.

Let me know what you think!

**Comment by daledude** [comment]
@sverweij 
Thanks for the feature! It works as intended but highlights an issue with the entity box width. Notice [on this link](https://mscgen.js.org/?lang=xu&msc=msc%20%7B%0A%20%20width%3D%22auto%22%2C%0A%20%20wordwraparcs%3Dfalse%2C%0A%20%20wordwrapentities%3Dfalse%3B%0A%0A%20%20%22111.222.333.444%22%20%5Blabel%3D%22Echo%20144%5Cn111.222.333.444%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20SBC%20%5Blabel%3D%22%5CnSBC%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20%2255.555.555.555%22%20%5Blabel%3D%22TOOLS%5Cn55.555.555.555%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20%22666.66.666.666%22%20%5Blabel%3D%22please-dont-wrap%5Cn666.66.666.666%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20%22666.66.666.666%22%20%5Blabel%3D%22please%20extend%20box%20width%5Cn666.66.666.666%22%2C%20linecolor%3D%22%23c0c0c0%22%5D%2C%0A%20%20SPACER1%20%5Blinecolor%3D%22white%22%2C%20textcolor%3D%22white%22%2C%20arclinecolor%3D%22white%22%2C%20arctextcolor%3D%22%23c0c0c0%22%5D%3B%0A%0A%7D) that the last entity extends beyond the border. I notice all `rect` are set to width 100. Is it possible to auto extend the width of the entity `rect` to the size of the enclosed text? Or, allow me to change it through an arc option?

If just the entity box color were changeable I would set it to white and be done with it. But changing the `linecolor`, obviously, changes the whole line. And, changing the `entity` css class makes the line under the entity also disappear so there is a large gap between the entity and the lines. I'm not experienced enough to make the entity border just an underline.

**Comment by sverweij** [comment]
Auto-expanding the boxes to fit content - I have to think how to approach that (both functionally and technically). I also want to think about improving the line wrapping algorithm - because that's the root cause for this issue.

About making the border of entities transparent: there's currently two things you can do:

- Use the 'classic' theme - made to look like the original mscgen output. It doesn't paint borders around the entities (it also has 1px wide lines and arrows that are smaller though, so it might not be to your taste)
![image](https://cloud.githubusercontent.com/assets/4822597/24646746/40c2df6c-191d-11e7-8d94-e20b88d495e6.png)
- You already found out how to provide a css rule to make the line color of the `rect` around the entity white (note: `transparent` is also a color - it might better suit your need. It also puts the line two pixels closer to the text). As it's a `rect` (one shape) there is no way I know of to only draw the bottom.

**Comment by daledude** [comment]
Thanks for the `transparent` tip. That provides a good alternative to text extending outside the entity box.

Something you may already think about but anyway...At some point you won't be able to save a user from themselves regarding width problems with `wordwrapentities`. I think for this feature to be complete you would have to extend the boundaries of the non-wrapping entities until they get within certain pixel distance of their neighbors and then start to wrap. So, depending how much effort you want to put into this I, personally, would be ok dealing with the consequences of my text inevitably being to long and breaking display and finding a way to deal with that in my code. Similar to removing the box around the entity which actually makes the display cleaner.

**Comment by sverweij** [comment]
You're right, there'd be a need to put limits to expanding the box. 

I've been sketching a bit. 

This how it would look if the entity box just expands without boxes around it (1)
<img width="654" alt="screen shot 2017-04-05 at 21 29 19" src="https://cloud.githubusercontent.com/assets/4822597/24723240/0b8d762e-1a47-11e7-94f8-40b80b7b5589.png">

... with boxes
<img width="656" alt="screen shot 2017-04-05 at 21 11 46" src="https://cloud.githubusercontent.com/assets/4822597/24722645/d117869e-1a44-11e7-811b-993c7a6b441e.png">

An additional step is to keep the space between entity borders the same (2)
<img width="777" alt="screen shot 2017-04-05 at 20 55 34" src="https://cloud.githubusercontent.com/assets/4822597/24722661/dac739aa-1a44-11e7-9f8a-739bad3d0f0c.png">

My target is (2) - but I'll have to pass (1) anyway

**Comment by sverweij** [comment]
@daledude I have hacked something quick & irresponsible in core for (1) - would this work for you?

![haksel](https://cloud.githubusercontent.com/assets/4822597/24726195/ca8a4b10-1a51-11e7-85b8-2ce29c4643fe.gif)

If so I'll try to do some polishing in the coming days & publish 

(animation is a bit slow & choppy - sorry 'bout that)

**Comment by daledude** [comment]
That looks like it would certainly work.

**Comment by sverweij** [comment]
@daledude I've published new versions to npm and mscgen.js.org with the entity width scaling. Let me know how it works out for you.

**Comment by daledude** [comment]
Seems to work great so far. Thanks!
