### ISSUE TITLE
watermark tag omitted in mscgenjs API version for ATOM

### ISSUE THREAD

**Issue by bmoesdijk** [sverweij/mscgen_js#260]
### Steps to Reproduce (for bugs)

1. Install the ATOM application in a MAC 
2. install the mscgenjs API from the ATOM package installer
3. open a new file in ATOM and type msc { watermark="my watermark"; a,b; a=>b;}
4. This will generate an mscgenjs API error on watermark=

### Context

* Version used: ATOM 1.40.1 x64 with latest mscgenjs API package installed
* Browser Name and version: N.A.
* Operating System and version (desktop or mobile): MAC OSX
* Link to your project:

**Comment by sverweij** [comment]
`watermark` is a feature not available in the [original mscgen](http://www.mcternan.me.uk/mscgen/), but only in `xù` - which is a super set of mscgen. If your file name ends with `.mscgen`, atom will assume mscgen syntax, but you need the xù one here. You can do this in one of these ways

- after opening yourchart.mscgen - pick Xù from the language menu before opening the preview.
- rename yourchart so it has the .xu suffix - in this case atom will automatically detect the xù interpreter.

(this behavior is different from the website which sort-of autodetects xu vs mscgen - sorry for the confusion!)

**Comment by bmoesdijk** [comment]
Our MailScanner believes that the attachment to this message sent to you
