### ISSUE TITLE
Feature request for virtual arc (arrow up/down)

### ISSUE THREAD

**Issue by bmoesdijk** [sverweij/mscgen_js#261]
### Steps to Reproduce (for bugs)
N.A.

### Context
example UML mscgen code:
msc {
  arcgradient=20, hscale=0.6;
  a [label="",linecolor="white"],
  b [label="", linecolor="white"],
  c [label="", linecolor="white"];

  b rbox b [label="textBox 1b", linecolor="grey", textbgcolor="grey"],
  b => a [arcskip="2", linecolor="black"],
  b => c [arcskip="2", linecolor="black"],
  **b => b [arcskip="90", linecolor="black"];** /* Should draw a vertical line over b from one step to the next. (in this example the 2 rbox-es on b; 1b -> 2b)
  |||;
  a rbox a [label="textBox 2a", linecolor="grey", textbgcolor="grey"],
  b rbox b [label="testBox 2b", linecolor="green",textbgcolor="green"],
  c rbox c [label="testBox 2c", linecolor="green",textbgcolor="green"];
}

### Your Environment

* Version used: ATOM with mscgenjs API and web interface at: https://mscgen.js.org
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sverweij** [comment]
The chart I get from your msc looks like a graph:

![untitled](https://user-images.githubusercontent.com/4822597/64859388-61d79680-d62a-11e9-96df-4f923a6f43b0.png)

Is it intentional to get a graph like representation? What is it you want to accomplish?

**Comment by bmoesdijk** [comment]
Our MailScanner believes that the attachment to this message sent to you

**Comment by bmoesdijk** [comment]
This is what I would like to accomplish.
![Screen Shot 2019-09-20 at 17 40 09](https://user-images.githubusercontent.com/29605411/65340120-d5027f00-dbcd-11e9-8728-b41e37c7b2b3.png)


As you can see in the example diagram above the vertical line in the middle is currently not possible to draw.
With the support of a vertical line it allows me to draw UML like diagrams. E.g. hierarchical diagrams or organograms, etc.

**Comment by sverweij** [comment]
If you want to accomplish that you might be better of with a tool that is geared towards graph modelling:
- [GraphViz](http://www.graphviz.org) is excellent for that - you can try it online at [viz-js](http://viz-js.com),  and in the atom editor with the [graphviz-preview-plus](https://atom.io/packages/graphviz-preview-plus) package.
- If you're looking for something conceptually higher level than graphviz you can consider
  - [nomnoml](http://www.nomnoml.com) - which is also text based and seems to have a nice layout algorithm 
  - If you're into writing UML state machines you could use [state machine cat](https://state-machine-cat.js.org) (atom package:  [state-machine-cat-preview](https://atom.io/packages/state-machine-cat-preview))- which I wrote for that purpose.

**Comment by bmoesdijk** [comment]
Thanks a lot! I will have a look at these alternatives

Kind regards
Boudewijn
