### ISSUE TITLE
[ Help Wanted ] Add padding for rbox

### ISSUE THREAD

**Issue by rick-chou** [sverweij/mscgen_js#266]
Hey ! Is there possible to add the padding for rbox ?

**Comment by sverweij** [comment]
Hi @rick-chou - there's not an option to set this directly. There might be options that help out with solving layout issues, though. What is it you're bumping into? Do you have an example?

**Comment by rick-chou** [comment]
THX! For Example

```text
msc{
  wordwraparcs=1,
  hscale=1.2;

  TIME [label="", arclinecolor="transparent", linecolor="white"],
  EMPTY1 [label="", arclinecolor="transparent", linecolor="white"],
  A [
    label="A", 
    linecolor="#ffb000",
    textbgcolor="#ffb000",
    arclinecolor="#ffb000",
    arctextcolor="#ffb000"
  ];


    TIME => A [label="2023-07-04/06:45:55.971"], 
    A rbox A [label="xxxxxx_xxxxxx_xxxxxxx = false, xxxxxx_xxxxxx_xxxxxxx = false,xxxxxx_xxxxxx_xxxxxxx = true"];|||;
}
```
<img width="1506" alt="Screenshot 2023-09-04 at 09 43 26" src="https://github.com/sverweij/mscgen_js/assets/56244178/c91f0cc1-272c-4141-9064-2011c67d4abe">

I wish the boxes here were bigger so the user interface would be more comfortable.

**Comment by rick-chou** [comment]
It seems to be able to be resized via `hscale`, but I can't make sure that the text is long enough here to do a good job of fitting. I'll close this issue, thanks Anaway.
